.TH PARCELLITE 1 "March 17 2008"
.SH NAME
Parcellite \- Lightweight GTK+ Clipboard Manager
.SH SYNOPSIS
.B parcellite
[\fIOPTION\fR]
.SH DESCRIPTION
\fBParcellite\fR is a lightweight GTK+ clipboard manager. This is a stripped down,
basic\-features\-only clipboard manager with a small memory footprint for those
who like simplicity.

\fBParcellite\fR features a clipboard CLI. Unrecognized options and the contents
of your standard input get copied to your clipboard. See \fBCLI EXAMPLES\fR.
.SH
.B OPTIONS
.TP
.B \-?\fR, \fB\-\-help
Show help options
.TP
.B \-d\fR, \fB\-\-daemon
Run as daemon. Use this mode if you just want \fBParcellite\fR to keep your clipboard
and primary contents safe
.TP
.B \-n\fR, \fB\-\-no-icon
Do not use status icon
.TP
.B \-c\fR, \fB\-\-clipboard
Print clipboard contents
.B \-p\fR, \fB\-\-primary
Print primary contents
.SH ACTIONS
\fBParcellite's\fR actions perform commands using the contents of your clipboard. "\fB%s\fR" in the command
is replaced with the clipboard contents.
.SH CLI EXAMPLES
 echo "copied to clipboard" | parcellite
 parcellite "copied to clipboard"
 echo "copied to clipboard" | parcellite \-c
.SH Hotkeys
 The available hotkey modifiers are <Ctrl>, <Alt> <Shift>, <Release>, <Meta>, <Super>, <Hyper>, <Mod[1\-5]>
.SH Preferences
Right-click on the parcellite icon in the systray to access the preferences.

.SH Behavior Tab
.TP 
.B Clipboards 
generally checking all these boxes is appropriate.
.TP 
.B History 
 Check 'Save history' to save history on close.
 'Items in History' - set maximum items. Currently limited to 100.
.SH Display Tab
.TP 
 'Show in Single line' does nothing
.TP 
 'Show in reverse order' reverses the history so the first entry is last and the last is first.
.TP 
 'Omit items' referrs to omitting characters that don't fit in the history window width. This is for display only.
.SH SEE ALSO
.PP
Website: http://parcellite.sourceforge.net
.SH AUTHOR
Written by Gilberto "Xyhthyx" Miralla <xyhthyx@gmail.com>. Gilberto is no longer maintaining the project. 'Rickyrockrat' is his replacement.
.SH BUGS
Please include your ~/.config/parcellite/parcelliterc file when filing a bug.  This will give me your preferences.
 Please report any bugs to the bug tracker via this web page:
 http://sourceforge.net/projects/parcellite/support
 Use the 'Bugs' under project trackers to file a bug if you are registered with Source Forge. If not, email rickyrockrat
(rickyrockrat at users.sourceforge.net), or click the 'project administers' in the link above.

